# My attempt at the whole digits example
I had to use the original code as a reference sometimes, especially to get method names and paths, but overall I tried hard to make this not a complete copy, though technically it has all of the same code...

Anyway, first, we have to import 3 things:

datasets, to get the digits dataset,

svm, to get the SVC classifier,

and metrics, to generate a classification report.

In [1]:
from sklearn import datasets, svm, metrics

Next, we have to load the digits dataset, and set it to a variable.

In [2]:
digits = datasets.load_digits()

Next, we need to turn all the images into a form we can do stuff with. Currently, they are in a 2D array, of opacity values or something like that, I don't know... anyway, we need to turn this into a 1D array, so we use the reshape method:

In [3]:
num_digits = len(digits.images)
data = digits.images.reshape((num_digits,-1))

Next, we set up the classifier! I have no idea what gamma does, but the other guys did it, so I thought it would be a good idea! We are using an SVC classifier, since I don't know any other classifiers, so yeah!

After we set up the classifier, we train classifier using the first half of the image data and the first half of the digits.target array. Digits.target contains the desired outputs, basically stating what number each image actually contains.

You can also see all the information about the classifier in the output, but I don't know what that means and scikit-learn uses a bunch of jargon that I don't understand, so I won't go over these.

In [4]:
classifier = svm.SVC(gamma=0.001)
classifier.fit(data[:num_digits/2],digits.target[:num_digits/2])

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

Next, we create two arrays:

Expected contains the target digits in each image in the second half of the dataset, so basically the goal for each image.

Predicted contains the digits that the classifier predicted from the second half of the dataset. If the classifier was perfect, the values in the predicted array would completely equal the values in the expected array.

In [5]:
expected = digits.target[num_digits/2:]
predicted = classifier.predict(data[num_digits/2:])

Now that we have all of the data on our predictions, we can visualize it and stuff! Here, we generate a classification report basically stating how well we did using some function in scikit-learn.

In [6]:
print(metrics.classification_report(expected,predicted))

             precision    recall  f1-score   support

          0       1.00      0.99      0.99        88
          1       0.99      0.97      0.98        91
          2       0.99      0.99      0.99        86
          3       0.98      0.87      0.92        91
          4       0.99      0.96      0.97        92
          5       0.95      0.97      0.96        91
          6       0.99      0.99      0.99        91
          7       0.96      0.99      0.97        89
          8       0.94      1.00      0.97        88
          9       0.93      0.98      0.95        92

avg / total       0.97      0.97      0.97       899



We can also output the confusion matrix from here. Now that I know what a confusion matrix is, as well as all of the crazy values above this block of text, I think these things are really nice and helpful!

In [7]:
print(metrics.confusion_matrix(expected,predicted))

[[87  0  0  0  1  0  0  0  0  0]
 [ 0 88  1  0  0  0  0  0  1  1]
 [ 0  0 85  1  0  0  0  0  0  0]
 [ 0  0  0 79  0  3  0  4  5  0]
 [ 0  0  0  0 88  0  0  0  0  4]
 [ 0  0  0  0  0 88  1  0  0  2]
 [ 0  1  0  0  0  0 90  0  0  0]
 [ 0  0  0  0  0  1  0 88  0  0]
 [ 0  0  0  0  0  0  0  0 88  0]
 [ 0  0  0  1  0  1  0  0  0 90]]


Pretty much all the other stuff in the example is the plotting code and stuff they used so that they could create visualizations of training data and predictions at the bottom as examples, but I really don't care about any of that, and plotting is such a pain that I really don't want to learn all of those functions. Anyway, yeah! I (mostly) understand the example now!